#
# (c) Copyright 2020 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Wrapper task used to manage running rabbitmq start/stop during upgrade
# operations.
# NOTE: Requires that the rabbitmq role has been loaded at some point prior
# to including this task
---

# Stop messages entering a node by blocking the '*_listener' ports.
# Need to do this here to:
#   * stop traffic entering a node which we are stopping, giving
#     and early indication to the proxy to move any vips pointing
#     at this node
#   * block trafficing entering a node we are starting that hasn't
#     yet fully joined the cluster
# the node
- include: "{{ playbook_dir }}/roles/iptables/tasks/iptables-add.yml"
  vars:
    iptables_chain: "{{ rabbitmq_iptables_chain }}"
    iptables_ip_port: "{{ rabbitmq_bind_addresses }}"

- include: "{{ playbook_dir }}/roles/rabbitmq/tasks/{{ rmq_upgrade_action }}.yml"

# Remove block on '*_listener' ports.
- include: "{{ playbook_dir }}/roles/iptables/tasks/iptables-delete.yml"
  vars:
    iptables_chain: "{{ rabbitmq_iptables_chain }}"
    iptables_ip_port: "{{ rabbitmq_bind_addresses }}"

