#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

# Regather facts on all hosts in case of configuration changes that haven't
# been reflected in the fact cache
- include: ardana-refresh-facts.yml

- include: pbstart.yml
  vars:
    playbook_name: "ardana-update-pkgs.yml"

# Prevents the playbook being run on multiple targets
- hosts: resources
  roles:
    - ardana-upgrade-tools
  tasks:
  - include: roles/ardana-upgrade-tools/tasks/check-single-host.yml
    vars:
      playbook_name: "ardana-reboot.yml"

- include: osconfig-status.yml

- include: _ardana-update-base.yml
  vars:
    install_package_updates: true

# Report update status
- include: _ardana-update-status.yml

- include: pbfinish.yml
  vars:
    playbook_name: "ardana-update-pkgs.yml"
