#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---
- hosts: resources
  tasks:
    - name: ardana-replace-legacy-repos | Remove old repos
      become: yes
      zypper_repository:
        name: "{{ item }}"
        state: absent
      when: ansible_os_family | lower == 'suse'
      with_items:
        - openstack-newton
        - openstack-pike
        - cloud8-openstack-devel
        - cloud8-openstack-devel-staging
        - sles12sp3-network
        - powerdns
        - opensuse-leap-network
        - sle-12-ga-standard
        - sle-12-sp2-update-products-manager31-standard
        - sle-12-update-standard
        - SLES-SDK
        - SLES-OS
        - vertica

- hosts: localhost
  tasks:
    - name: ardana-replace-legacy-repos | Rename extras directory to avoid its reuse
      become: yes
      command: mv /opt/ardana_packager/ardana/sles12/zypper/extras /opt/ardana_packager/ardana/sles12/zypper/extras_legacy
      ignore_errors: true

- include: _osconfig-setup-repos.yml
