#
# (c) Copyright 2015 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Playbook for setting up the Configuration Processor on the deployer
---
- include_vars: "{{ playbook_dir }}/ardana_version.yml"
  when: deployer_media_legacy_layout|bool

- name: config-processor  | install | Update venv cache
  become: yes
  install_package:
    cache: update

- name: config-processor | install | Install the Configuration Processor
  become: yes
  when: deployer_media_legacy_layout|bool
  install_package:
    name: config_processor
    service: config-processor
    state: present
    activate: act_on

- name: config-processor | install | Create base log directory
  become: yes
  file:
    path: "{{ config_processor_install.log_dir }}"
    owner: "{{ ardanauser }}"
    group: "{{ ardanauser }}"
    state: directory
    mode: 0755

- name: config-processor | install | Create Configuration Processor log files
  become: yes
  file:
    path: "{{ item }}"
    owner: "{{ ardanauser }}"
    group: "{{ ardanauser }}"
    state: touch
    mode: 0755
  with_items:
    - "{{ config_processor_install.logfile_output }}"
    - "{{ config_processor_install.logfile_errors }}"

- name: config-processor | install | Copy Configuration Processor Services into work dir
  when: deployer_media_legacy_layout|bool
  synchronize:
    src: "{{ config_processor_input_model_services_src }}"
    dest: "{{ config_processor_install_ardana }}"
    recursive: yes
  delegate_to: deployer

