#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Configure the bash shell we will be working in
---
- set_fact:
    bashrc_path="{{ ansible_env.HOME }}/.bashrc"

- stat: path=bashrc_path
  register: bashrc

- name: deployer-setup | configure-bash | Unset HISTCONTROL in the environment
  replace:
    dest=bashrc_path
    regexp="HISTCONTROL=[\w]*"
    replace="HISTCONTROL="
  when: bashrc.stat.exists is defined and bashrc.stat.exists

- name: deployer-setup | configure-bash | HISTCONTROL comment fixing
  replace:
    dest=bashrc_path
    regexp="don\'t put duplicate lines or lines starting with space in the history"
    replace="do not filter out any command from the history"
  when: bashrc.stat.exists is defined and bashrc.stat.exists
