#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: deployer-setup | init-deployer-from-iso | Check target version needed
  stat:
    path: "{{ delta_target_version_file }}"
  register: check_target_version_needed

- name: deployer-setup | init-deployer-from-iso | Check target version matches
  shell: diff {{ delta_target_version_file }} {{ ardana_version_file }}
  when: check_target_version_needed.stat.exists
  ignore_errors: true
  register: ardana_version_check_result

- name: deployer-setup | init-deployer-from-iso | Get target version
  shell: grep "^Ardana OpenStack" {{ ardana_version_file }} | grep -o 'build .*-[0-9TZ]*'
  when: ardana_version_check_result|failed
  register: ardana_version_target

- name: deployer-setup | init-deployer-from-iso | Get current version
  shell: grep "^Ardana OpenStack" {{ delta_target_version_file }} | grep -o 'build .*-[0-9TZ]*'
  when: ardana_version_check_result|failed
  register: ardana_version_current

- name: deployer-setup | init-deployer-from-iso | Report version check fails
  fail: msg="This kit is an upgrade kit {{ ardana_version_target.stdout }} and you do not have the pre-requisite version. You are running version {{ ardana_version_current.stdout }}. Please download a full kit instead."
  when: ardana_version_check_result|failed

#TODO-Cian: Remove file check once hlinux repo is on deployer by default
- name: deployer-setup | init-deployer-from-iso | Check for hlinux repo pool directory
  stat: path={{ hlinux_apt_repo_loc }}/pool
  register: hlinux_pool_dir

- name: deployer-setup | init-deployer-from-iso | Do we have an hlinux repo
  set_fact: hlinux_repo_available={{ hlinux_pool_dir.stat.exists }}

- name: deployer-setup | init-deployer-from-iso | Add apt proxy config for local repo
  become: yes
  copy: src=06apt-hlinux.conf dest=/etc/apt/apt.conf.d/06apt-hlinux.conf
  when: hlinux_repo_available

- name: deployer-setup | init-deployer-from-iso | Install dpkg-dev
  become: yes
  apt: name=dpkg-dev state=present
  when: hlinux_repo_available

- name: deployer-setup | init-deployer-from-iso | Remove old sources.list.d files
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/etc/apt/sources.list.d/*"
  when: hlinux_repo_available

- name: deployer-setup | init-deployer-from-iso | Create hlinux apt repo directory
  become: yes
  file: path={{ hlinux_apt_repo_dir }} state=directory mode=0755
  when: hlinux_repo_available

- name: deployer-setup | init-deployer-from-iso | Create foreign apt repo directory
  become: yes
  file: path={{ foreign_apt_repo_dir }} state=directory mode=0755
  when: hlinux_repo_available

- name: deployer-setup | init-deployer-from-iso | Check if hlinux ident exists
  stat: path={{ hlinux_apt_repo_loc }}/.disk/info
  register: hlinux_ident_file

- name: deployer-setup | init-deployer-from-iso | Copy ident file
  become: yes
  copy: src={{ hlinux_apt_repo_loc }}/.disk/info dest={{ hlinux_apt_repo_dir }}/info
  when: hlinux_ident_file.stat.exists

- name: deployer-setup | check-package-backup-needed | Check if this is an upgrade kit
  stat:
    path: "{{ dupe_files_loc }}"
  register: package_backup_needed
  when: hlinux_repo_available

- name: deployer-setup | init-deployer-from-iso | Backup apt repo packages
  become: yes
  shell: tar -rf "{{ hlinux_apt_backup_loc }}" -T {{ dupe_files_loc }}
  args:
    chdir: "{{ hlinux_apt_repo_dir }}"
  when: hlinux_repo_available and package_backup_needed.stat.exists

- name: deployer-setup | init-deployer-from-iso | Rsync hlinux apt repo
  become: yes
  synchronize:
    src: "{{ hlinux_apt_repo_loc }}/{{ item }}"
    dest: "{{ hlinux_apt_repo_dir }}"
    delete: true
    times: no
  with_items:
    - pool
    - dists
  when: hlinux_repo_available

- name: deployer-setup | init-deployer-from-iso | Restore backed up apt repo packages
  become: yes
  unarchive:
    src: "{{ hlinux_apt_backup_loc }}"
    dest: "{{ hlinux_apt_repo_dir }}"
    copy: no
  when: hlinux_repo_available and package_backup_needed.stat.exists

- name: deployer-setup | init-deployer-from-iso | Remove backup file
  become: yes
  file:
    path: "{{ hlinux_apt_backup_loc }}"
    state: absent
  when: hlinux_repo_available and package_backup_needed.stat.exists

- name: deployer-setup | init-deployer-from-iso | Backup iso netboot area
  become: yes
  synchronize:
    src: "{{ hlinux_apt_repo_dir }}/dists/{{ hlinux_distro }}/main/installer-amd64/current/images/netboot"
    dest: "{{ hlinux_apt_repo_dir }}/dists/{{ hlinux_distro }}/main/installer-amd64/current/images/netboot.iso"
    delete: yes
  when: hlinux_repo_available

- name: deployer-setup | init-deployer-from-iso | Remove bad netboot area
  become: yes
  file:
    path: "{{ hlinux_apt_repo_dir }}/dists/{{ hlinux_distro }}/main/installer-amd64/current/images/netboot"
    state: absent
  when: hlinux_repo_available

- name: deployer-setup | init-deployer-from-iso | Create good netboot area
  become: yes
  file:
    path: "{{ hlinux_apt_repo_dir }}/dists/{{ hlinux_distro }}/main/installer-amd64/current/images/netboot"
    state: directory
  when: hlinux_repo_available

# Copy the grubnet into /var/lib/cobbler/loaders
- name: deployer-setup | init-deployer-from-iso | get netbootgrub
  set_fact: hlinux_grubnet={{ item }}
  with_fileglob: "{{ grub_net_glob }}"

- name: deployer-setup | init-deployer-from-iso | create netboot destination
  become: yes
  file: path=/var/lib/cobbler/loaders state=directory mode=0755
  when: hlinux_repo_available

# The name of the tarball changes on every hLinux respin so we have to search for it.
- name: deployer-setup | init-deployer-from-iso | Find netboot tarball
  set_fact: hlinux_netboot_tarball={{ item }}
  with_fileglob: "{{ netboot_tarball_glob }}"

- name: deployer-setup | init-deployer-from-iso | Populate good netboot area
  become: yes
  unarchive:
    src: "{{ hlinux_netboot_tarball }}"
    dest: "{{ hlinux_apt_repo_dir }}/dists/{{ hlinux_distro }}/main/installer-amd64/current/images/netboot"
  when: hlinux_repo_available

- name: deployer-setup | init-deployer-from-iso | Add deployer repo to sources.list
  become: yes
  apt_repository: repo={{ hlinux_repo_source }} state=present
  when: hlinux_repo_available

# We always need to execute this, because the "with_items" on cdrom_sources.stdout_lines
# further down this file will fail if it doesn't exist. It can be empty, that's fine.
- name: deployer-setup | init-deployer-from-iso | Retrieve list of cdrom sources
  shell: |
    set -eu
    if [ -e "/etc/apt/sources.list" ]; then
        /usr/bin/awk '($1 ~ "^deb") && ($2 ~ "^cdrom:" || $3 ~ "^cdrom:") {print $0}' /etc/apt/sources.list
    fi
  register: cdrom_sources

- name: deployer-setup | init-deployer-from-iso | Remove cdrom install sources
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: absent
  with_items: "{{ cdrom_sources.stdout_lines }}"
  when: hlinux_repo_available

- name: deployer-setup | init-deployer-from-iso | Add i386 architecture to the deployer dpkg
  become: yes
  command: dpkg --add-architecture i386
  when: hlinux_repo_available

- name: deployer-setup | init-deployer-from-iso | Run apt-get update to reload sources
  become: yes
  shell: |
    apt-get update
  when: hlinux_repo_available

- name: deployer-setup | init-deployer-from-iso | check if qcow2 exists
  become: yes
  stat:
     path: "{{ deployer_setup_hlinux_qcow2 }}"
  register: result_hlinux_qcow2_file

- name: deployer-setup | init-deployer-from-iso | mkdir stage for qcow2
  file:
     path: "{{ deployer_setup_qcow2_path }}"
     state: directory

- name: deployer-setup | init-deployer-from-iso | copy qcow2 from iso
  become: yes
  command: cp "{{ deployer_setup_hlinux_qcow2 }}" "{{ deployer_setup_qcow2_path }}"
  when: result_hlinux_qcow2_file.stat.exists

- name: deployer-setup | init-deployer-from-iso | check if OVA exists
  become: yes
  stat:
     path: "{{ hlinux_ova_path }}"
  register: hlinux_ova_file_result

- name: deployer-setup | init-deployer-from-iso | mkdir ova_images for OVA
  become: yes
  file:
     path: "{{ target_ova_location }}"
     state: directory

- name: deployer-setup | init-deployer-from-iso | copy OVA from iso
  become: yes
  copy: src="{{ hlinux_ova_path }}" dest="{{ target_ova_location }}"
  when: hlinux_ova_file_result.stat.exists
