#
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

---

# include with with_items is deprecated/removed in ansible 1.9.6

- include: "find-iso.yml"
  vars:
    find_iso_header: "SLES 12 SP3 Server"
    find_iso_file: "{{ ardanauser_home }}/{{ deployer_sles12_iso }}"
    find_iso_mount_dir: "/media/cdrom"
    find_iso_marker_file: "media.1/products"
    find_iso_marker_file_line: " SLES12-SP3 "
    find_iso_target_dir:
      "{{ PACKAGE_CONSTANTS.REPO_DIR }}/ardana/sles12/zypper/OS"

- include: "find-iso.yml"
  vars:
    find_iso_header: "SLES 12 SP3 Server"
    find_iso_file: "{{ ardanauser_home }}/{{ deployer_sles12_iso }}"
    find_iso_mount_dir: "/media/sles"
    find_iso_marker_file: "media.1/products"
    find_iso_marker_file_line: " SLES12-SP3 "
    find_iso_target_dir:
      "{{ PACKAGE_CONSTANTS.REPO_DIR }}/ardana/sles12/zypper/OS"

- include: "find-iso.yml"
  vars:
    find_iso_header: "SLES 12 SP3 SDK"
    find_iso_file: "{{ ardanauser_home }}/{{ deployer_sles12sdk_iso }}"
    find_iso_mount_dir: "/media/sdk"
    find_iso_marker_file: "media.1/products"
    find_iso_marker_file_line: " SDK12-SP3 "
    find_iso_target_dir:
      "{{ PACKAGE_CONSTANTS.REPO_DIR }}/ardana/sles12/zypper/SDK"

- include: "find-iso.yml"
  vars:
    find_iso_header: "SLES 12 SP3 SDK"
    find_iso_file: "{{ ardanauser_home }}/{{ deployer_sles12sdk_iso }}"
    find_iso_mount_dir: "/media/sles_sdk"
    find_iso_marker_file: "media.1/products"
    find_iso_marker_file_line: " SDK12-SP3 "
    find_iso_target_dir:
      "{{ PACKAGE_CONSTANTS.REPO_DIR }}/ardana/sles12/zypper/SDK"

- include: "find-iso.yml"
  vars:
    find_iso_header: "Red Hat Enterprise Linux"
    find_iso_file: "{{ ardanauser_home }}/{{ deployer_rhel7_iso }}"
    find_iso_mount_dir: "/media/rhel"
    find_iso_marker_file: ".discinfo"
    find_iso_marker_file_line: "Red Hat Enterprise Linux "
    find_iso_target_dir:
      "{{ PACKAGE_CONSTANTS.REPO_DIR }}/ardana/rhel7/yum/OS"
