#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# We need the /opt/ardana_packager directory populate so that we have
# the packager-1.tgz file to expand.
---
- include_vars: ../defaults/ardana_tar_locations.yml

- name: deployer-setup | install-venv-contents | Test we are include venv packages to for the os
  stat:
    path: "{{ ardanauser_home }}/{{ item.value }}"
  with_dict: deployer_venv_tarballs
  register: _venv_tar_result

- name: deployer-setup | install-venv-contents | Ensure venv os dir exits exists
  become: yes
  file:
    path: "{{ PACKAGE_CONSTANTS.REPO_DIR }}/{{ ardana_version }}/{{ package_venv_locations[item.item.key][ansible_architecture] }}"
    state: directory
  when: item.stat.exists
  with_items: _venv_tar_result.results

- name: deployer-setup | install-venv-contents | Unarchive venvs to os dir
  become: yes
  unarchive:
    src: "{{ ardanauser_home }}/{{ item.item.value }}"
    dest: "{{ PACKAGE_CONSTANTS.REPO_DIR }}/{{ ardana_version }}/{{ package_venv_locations[item.item.key][ansible_architecture] }}"
    owner: root
    group: root
    copy: no
  when: item.stat.exists
  with_items: _venv_tar_result.results
