#
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Playbook for setting up the installui on the deployer
---

- name: installui | configure | Create installui.service.d directory
  become: yes
  file:
    path: "{{ systemd_config_dir }}"
    state: directory

- name: installui | configure | Create ardana installer temp directory
  become: yes
  file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0700
    owner: "{{ ardanauser }}"
    group: "{{ ardanauser }}"

- name: installui | configure | Apply systemd template
  become: yes
  template:
    src: "local.conf.j2"
    dest: "{{ systemd_config_file }}"
  notify: installui_change

- name: installui | install | Clear old directory
  become: yes
  file:
    state: absent
    path: "{{ installui_directory }}"
    owner: "{{ ardanauser }}"
    group: "{{ ardanauser }}"
    mode: 0775
    state: directory

# unclear what this does or if its required
- name: installui | install | Update venv cache
  become: yes
  install_package:
    cache: update

- name: installui | install | Install Cloud Installer UI
  become: yes
  install_package:
    name: installui
    service: installui
    state: present
    activate: act_on
  notify: installui_change

- name: installui | install | Extract Install UI service files
  become: yes
  unarchive:
    dest: "{{ installui_directory }}"
    src: "{{ item }}"
    copy: no
    owner: "{{ ardanauser }}"
    group: "{{ ardanauser }}"
    mode: 0644
  with_fileglob:
    - "{{ 'installui' | jar_dir }}/cloudinstaller-*.tgz"

# Directories need to be executable for GUI to access files
- name: installui | install | Set permission on directories to be executable
  become: yes
  command: find {{ installui_directory }} -type d -exec chmod 0755 {} +

# the Systemd setup command assumes a /venv/bin location for commands
- name: installui | install | Create fake venv bin directory
  become: yes
  file:
    path: "{{ installui_directory }}/venv/bin"
    owner: "{{ ardanauser }}"
    group: "{{ ardanauser }}"
    state: directory

- name: installui | install | Setup Install UI service
  become: yes
  setup_systemd:
    service: installui
    user: "{{ ardanauser }}"
    group: "{{ ardanauser }}"
    install_dir: "{{ ardanauser_home }}"
    cmd: python
    args: >
      "{{ installui_directory }}/lib/python2.7/site-packages/cloudinstaller/main.py"

# Temporary HLINUX HACK! - copy the system python2.7 over the venv one
- name: installui | install | hlinux HACK copy system python2.7
  become: yes
  copy: src=/usr/bin/python2.7 dest={{ installui_directory }}/bin/python2.7
  when: ansible_os_family == 'Debian'

# symlink the "fake" python interpreter that systemd is looking for to the real one
- name: installui | install | Symlink Python2.7
  become: yes
  file:
    dest: "{{ installui_directory }}/venv/bin/python"
    src: "{{ installui_directory }}/bin/python"
    force: yes
    state: link

# Python2.7 binary in the venv needs to be excutable
- name: installui | install | Set permission on directories to be executable
  become: yes
  command: chmod +x {{ installui_directory }}/bin/python2.7
