#
# (c) Copyright 2015 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

# Ensure that Ansible is being run from the right place.
# This role can be included in a playbook to ensure that
# various parts of the deployment lifecycle are being run
# from the appropriate place.

# Parameters:
#   location: a member of valid_dirs and warning.
#   valid_dirs:
#     ardana:
#       - {{ ardanauser_home }}/openstack/ardana/ansible
#   warning:
#     ardana: "Your warning message goes here."
---

- name: guard-runtime-location | main | Ensure we're running in an expected location.
  fail:
    msg: "{{ warning[location] }}"
  when: playbook_dir not in valid_dirs[location]
