#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- include_vars: "{{ playbook_dir }}/ardana_version.yml"
  when: deployer_media_legacy_layout|bool
# non-SUSE
- include_vars: "{{ ansible_os_family | lower }}.yml"
  when: not ansible_os_family | lower | search('suse')
# for openSUSE and SLES, import the same vars file
- include_vars: "suse.yml"
  when: ansible_os_family | lower | search('suse')
